ncihtan/data-models

.github/workflows/auto-convert.yml
- fixes #15 
The workflow will be triggered once the `HTAN.model.csv` file changes after a git push.
Example of Usage:
```
git checkout -b <your-feature-branch>
git add -A
git commit -m "update data model"
git push origin <your-feature-branch>
```
Once the workflow completes, you should see updated `HTAN.model.jsonld` in the `<your-feature-branch>`. 
Check the draft PR #17 to see an example.
=> Update CI/CD workflow to auto convert csv to jsonld

.github/ISSUE_TEMPLATE/update_data_model.md, README.md
This PR adds instructions to the `README.md` on the process to edit the data model, ensuring the `.jsonld` is correctly generated and opening a PR to have them considered.
=> Add instructions on how to update the data model

HTAN.model.csv
=> Imaging bug fixes

HTAN.model.csv
As required by [ncihtan/HTAN-datacurator issue #27](https://github.com/ncihtan/HTAN-data-curator/issues/27)
=> Remove int validation from FOV number

.github/workflows/ci-convert.yml
pull the updates from https://github.com/Sage-Bionetworks/data-models/pull/8
=> Update to use setup-python action

.github/workflows/add-to-project.yml
Follows: https://github.com/actions/add-to-project
Fixes #111
=> Create Add to project action

HTAN.model.csv
Fixes [ncihtan/data-release-tracker #486](https://github.com/ncihtan/data-release-tracker/issues/486)
=> Make `Yes - Is Lowest level` not required

HTAN.model.csv
=> Add data model fixes identified with CSV linting

HTAN.model.csv
=> Change valid value "Long read" to title case

HTAN.model.csv
This PR will add 'transcript' as a valid value for the attribute 'Imaging Object Class.'
=> Update Imaging Object Class Values

HTAN.model.csv
Model changed to include spot instead of transcript in Image Object Class due to validation issues.
=> Update with spot instead of transcript.

HTAN.model.csv
=> Added new attribute "Publication contains HTAN ID"

.github/workflows/ci-lint-validate-convert.yml
Combines our current two workflows into one, with the final conversion dependent on the lining and validation passing
=> Refine lint, validate and convert workflow

HTAN.model.csv
=> Refine filename validation rule

HTAN.model.csv
Closes https://github.com/ncihtan/data-models/issues/255
=> Move description of "Proportion of minimum CpG Coverage 10X" to correct column

HTAN.model.csv
Reverts ncihtan/data-models#256
=> Revert "Move description of "Proportion of minimum CpG Coverage 10X" to correct column"

HTAN.model.csv
=> Add list like validation for Imaging Object Class

HTAN.model.csv
=> Fix spots under tissue capitalization

HTAN.model.csv
=> Update regex validation for Filename

dca-template-config.json
Adds the DCA template JSON to this repo.
No data model impact so merging without review
=> Add DCA template JSON

.github/workflows/check_attributes_are_used.py
=> update ignored attributes list

dca-template-config.json
=> Add accessory template to dca-template-config.json

HTAN.model.csv
=> Fix DMR calling workflow validation

HTAN.model.csv
=> AccessoryManifest Modifications

.github/workflows/ci-lint-validate-convert.yml
=> Updating workflow to include IPython installation

dca-template-config.json
Closes #400 
Will require a release and a PR to the DCA config repo to get deployed.
=> Add Xenium and CosMX to DCA template config json

dca-template-config.json
=> Add microarray to config

.github/workflows/ci-lint-validate-convert.yml, .github/workflows/model-integrity-checks.yml, .github/workflows/schema-bq.yml
=> update actions to those using Node.js 20

HTAN.model.csv
Tied to issue: https://github.com/ncihtan/data-models/issues/431 
Add an additional valid value to the Antibody Role Attribute - "Neither - Dye/Stain" 
Add "Not Applicable" as valid value to RRID Identifier Attribute
=> Channel Metadata Model Updated

README.md
Mention data standard pages in the readme
=> Add link to standards page on README

.github/workflows/ci-lint-validate-convert.yml
- Adjusted triggers to include `pull_request` and `workflow_dispatch`: Ensured the workflow activates correctly when triggered by pull requests.
- Incorporated conditional steps for fetching and pushing changes: Applied conditions specifically for scenarios where the workflow is activated by a pull request.
- Removed `shell: bash` setting: This configuration was unnecessary as the default shell is automatically used, unless an alternative shell is required.
These adjustments aim to resolve the issue related to the undefined 'ref' in pull requests.
=> Workflow fix

HTAN.model.csv
=> Remove stripe calling validation rule

dca-template-config.json
=> Fix ExSeq Minimal Schema name
